---
title: "rCharts and Plotly Shiny Markdown"
author: "gjames"
date: "3 January 2016"
output: ioslides_presentation
runtime: shiny
---

## Shiny Presentation

This R markdown is adapted from the Shiny slides example, but to incorporate rCharts and Plotly as the plotting packages. I have once again used a loan tape from the Lending Club.

```{r, echo=FALSE,results='asis',comment=NA,warning=FALSE,message=FALSE}
library(data.table)
data <- data.table::fread("LoanStats3c.csv", header = TRUE, sep = ",")
library(plyr)
library(dplyr)
termGradeVals <- dplyr::group_by(data, c("term", "grade")) %>% plyr::ddply(c("term", "grade"), summarize, balance=sum(as.numeric(loan_amnt)))
library(rCharts)
tgPlot <- hPlot(balance ~ grade, group = "term", data = termGradeVals, type = "column")
tgPlot$plotOptions(series = list(stacking = "normal"))
tgPlot$legend(title = list(text = "Term"))
library(knitr)
opts_chunk$set(comment = NA, results = "asis", comment = NA, tidy = F)
tgPlot$show('iframesrc', cdn = TRUE)
```

## Slide with Interactive Plot

```{r, echo=FALSE,comment=NA,warning=FALSE,message=FALSE}
library(mvtnorm)
inputPanel(
  selectInput("obs", label = "Number of Observations:",
              choices = c(50, 100, 150, 200), selected = 50),
  
  sliderInput("corr", label = "Correlation of Copula:",
              min = 0.05, max = 0.95, value = 0.75, step = 0.05)
)

observations <- reactive({
  corr <- matrix(c(1, input$corr, input$corr,input$corr, 1, input$corr,input$corr, input$corr, 1), ncol = 3)
  obs <- mvtnorm::rmvnorm(as.numeric(input$obs), sigma = corr)
  obs <- setNames(data.frame(obs), c("x", "y", "z"))
  return(obs)
  })

library(plotly)
renderPlotly({plot_ly(observations(), x = x, y = y, z = z, type = "scatter3d", mode = "markers", color = x)})
```

## Information Slide

- Data Source: https://resources.lendingclub.com/LoanStats3c.csv.zip

## Slide with R Code and Output

```{r,echo=FALSE,comment=NA,warning=FALSE,message=FALSE}
gradeVals <- dplyr::group_by(data, c("grade", "sub_grade")) %>% plyr::ddply(c("grade", "sub_grade"), summarize, balance=sum(as.numeric(loan_amnt)))
d1 <- group_by(gradeVals, "grade") %>% ddply("grade", summarize, balance = sum(balance))
d2 <- group_by(gradeVals, "sub_grade") %>% ddply("sub_grade", summarize, balance = sum(balance))
d1 <- toJSONArray2(d1, json = F, name = F)
d2 <- toJSONArray2(d2, json = F, name = F)
pie <- Highcharts$new()
pie$chart(type = "pie")
pie$series(data = d1, size = "50%", dataLabels = list(enabled = FALSE))
pie$series(data = d2,  size = "80%", innerSize = "60%", replace = FALSE)
colors = "#! Highcharts.map(Highcharts.getOptions().colors, function(color) {
  return {
    radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
    stops: [
      [0, color],
      [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
      ]
}}) !#"
pie$plotOptions(pie=list(colors = colors))
pie$show('iframesrc', cdn = TRUE)
```


